<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Run_google_ads_iframe_22152718,16833_8cc2f2</name>
   <tag></tag>
   <elementGuidId>9d3f1ee7-1116-4af0-b725-2be8df57a001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;google_ads_iframe_\/22152718\,16833175\/sws-hb\/\/w3schools\.com\/\/try_it_leaderboard_0&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6a0dbdf4-7386-4639-a73d-83f51496c581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0</value>
      <webElementGuid>4d36e32a-92ce-486f-bd97-504a435c77de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0</value>
      <webElementGuid>7496e7af-cc76-409f-aee4-ea8f56ca1370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3rd party ad content</value>
      <webElementGuid>84e87b87-5c7e-49e3-91e9-ee4ccb3ab901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>728</value>
      <webElementGuid>63f430c2-508f-49af-97bd-54bc883d1a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>4b62720d-d911-4650-abdb-c75a420df90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>169e8c4b-25f0-4aa3-b317-f3ea753deafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4cfce1c5-07ef-4c24-8f87-a91bad35834c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1f7d524-ea08-4df9-ab37-22f1a56531a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>139e9914-9ad3-4a74-bb8e-4934b5742d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>cba95433-d5fd-4682-9e36-4082c6ad6e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>57b9fdce-cc20-4282-a3fc-c23556135fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>private-state-token-redemption;attribution-reporting</value>
      <webElementGuid>dc6a3b5e-9cc4-4a73-8f35-dff79925205e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9b3a1d6f-18b5-40bb-a8ce-6a5929fb389c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e11af90b-6759-4230-85f8-2bf1fe3b3a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0&quot;)</value>
      <webElementGuid>4e0de88e-a1c0-4904-bbf9-196ecdca1adf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0']</value>
      <webElementGuid>f98f0e56-3e6c-4ffb-a8a4-60780dd99833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0__container__']/iframe</value>
      <webElementGuid>16c4907b-d4a8-4e72-8a54-61f88e467a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>976da6dd-72eb-4b61-9359-6075a88cd4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0' and @name = 'google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0' and @title = '3rd party ad content']</value>
      <webElementGuid>52292311-3c0e-4ce8-9aaa-a550156b23e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
